// 时区城市数据（来自 CozyCc）
window.__TZ_CITIES = [["阿富汗", "Afghanistan", "Asia/Kabul", "+93", ["阿富汗", "afghanistan", "asia/kabul", "+93"]],
["亚美尼亚", "Armenia", "Asia/Yerevan", "+374", ["亚美尼亚", "armenia", "asia/yerevan", "+374"]],
["阿塞拜疆", "Azerbaijan", "Asia/Baku", "+994", ["阿塞拜疆", "azerbaijan", "asia/baku", "+994"]],
["巴林", "Bahrain", "Asia/Qatar", "+973", ["巴林", "bahrain", "asia/qatar", "+973"]],
["孟加拉国", "Bangladesh", "Asia/Dhaka", "+880", ["孟加拉国", "bangladesh", "asia/dhaka", "+880"]],
["不丹", "Bhutan", "Asia/Thimphu", "+975", ["不丹", "bhutan", "asia/thimphu", "+975"]],
["文莱", "Brunei", "Asia/Brunei", "+673", ["文莱", "brunei", "asia/brunei", "+673"]],
["柬埔寨", "Cambodia", "Asia/Bangkok", "+855", ["柬埔寨", "cambodia", "asia/bangkok", "+855"]],
["中国", "China", "Asia/Shanghai", "+86", ["中国", "china", "asia/shanghai", "+86"]],
["格鲁吉亚", "Georgia", "Asia/Tbilisi", "+995", ["格鲁吉亚", "georgia", "asia/tbilisi", "+995"]],
["中国香港", "Hong Kong", "Asia/Hong_Kong", "+852", ["中国香港", "hong kong", "asia/hong_kong", "+852"]],
["印度", "India", "Asia/Kolkata", "+91", ["印度", "india", "asia/kolkata", "+91"]],
["印度尼西亚", "Indonesia", "Asia/Jakarta", "+62", ["印度尼西亚", "indonesia", "asia/jakarta", "+62"]],
["伊朗", "Iran", "Asia/Tehran", "+98", ["伊朗", "iran", "asia/tehran", "+98"]],
["伊拉克", "Iraq", "Asia/Baghdad", "+964", ["伊拉克", "iraq", "asia/baghdad", "+964"]],
["以色列", "Israel", "Asia/Jerusalem", "+972", ["以色列", "israel", "asia/jerusalem", "+972"]],
["日本", "Japan", "Asia/Tokyo", "+81", ["日本", "japan", "asia/tokyo", "+81"]],
["约旦", "Jordan", "Asia/Amman", "+962", ["约旦", "jordan", "asia/amman", "+962"]],
["哈萨克斯坦", "Kazakhstan", "Asia/Almaty", "+7", ["哈萨克斯坦", "kazakhstan", "asia/almaty", "+7"]],
["朝鲜", "North Korea", "Asia/Pyongyang", "+850", ["朝鲜", "north korea", "asia/pyongyang", "+850"]],
["韩国", "South Korea", "Asia/Seoul", "+82", ["韩国", "south korea", "asia/seoul", "+82"]],
["科威特", "Kuwait", "Asia/Riyadh", "+965", ["科威特", "kuwait", "asia/riyadh", "+965"]],
["吉尔吉斯斯坦", "Kyrgyzstan", "Asia/Bishkek", "+996", ["吉尔吉斯斯坦", "kyrgyzstan", "asia/bishkek", "+996"]],
["老挝", "Laos", "Asia/Bangkok", "+856", ["老挝", "laos", "asia/bangkok", "+856"]],
["黎巴嫩", "Lebanon", "Asia/Beirut", "+961", ["黎巴嫩", "lebanon", "asia/beirut", "+961"]],
["中国澳门", "Macau", "Asia/Macau", "+853", ["中国澳门", "macau", "asia/macau", "+853"]],
["马来西亚", "Malaysia", "Asia/Kuala_Lumpur", "+60", ["马来西亚", "malaysia", "asia/kuala_lumpur", "+60"]],
["马尔代夫", "Maldives", "Indian/Maldives", "+960", ["马尔代夫", "maldives", "indian/maldives", "+960"]],
["蒙古", "Mongolia", "Asia/Ulaanbaatar", "+976", ["蒙古", "mongolia", "asia/ulaanbaatar", "+976"]],
["缅甸", "Myanmar", "Asia/Yangon", "+95", ["缅甸", "myanmar", "asia/yangon", "+95"]],
["尼泊尔", "Nepal", "Asia/Kathmandu", "+977", ["尼泊尔", "nepal", "asia/kathmandu", "+977"]],
["阿曼", "Oman", "Asia/Dubai", "+968", ["阿曼", "oman", "asia/dubai", "+968"]],
["巴基斯坦", "Pakistan", "Asia/Karachi", "+92", ["巴基斯坦", "pakistan", "asia/karachi", "+92"]],
["巴勒斯坦", "Palestine", "Asia/Gaza", "+970", ["巴勒斯坦", "palestine", "asia/gaza", "+970"]],
["菲律宾", "Philippines", "Asia/Manila", "+63", ["菲律宾", "philippines", "asia/manila", "+63"]],
["卡塔尔", "Qatar", "Asia/Qatar", "+974", ["卡塔尔", "qatar", "asia/qatar", "+974"]],
["沙特阿拉伯", "Saudi Arabia", "Asia/Riyadh", "+966", ["沙特阿拉伯", "saudi arabia", "asia/riyadh", "+966"]],
["新加坡", "Singapore", "Asia/Singapore", "+65", ["新加坡", "singapore", "asia/singapore", "+65"]],
["斯里兰卡", "Sri Lanka", "Asia/Colombo", "+94", ["斯里兰卡", "sri lanka", "asia/colombo", "+94"]],
["叙利亚", "Syria", "Asia/Damascus", "+963", ["叙利亚", "syria", "asia/damascus", "+963"]],
["中国台湾", "Taiwan", "Asia/Taipei", "+886", ["中国台湾", "taiwan", "asia/taipei", "+886"]],
["塔吉克斯坦", "Tajikistan", "Asia/Dushanbe", "+992", ["塔吉克斯坦", "tajikistan", "asia/dushanbe", "+992"]],
["泰国", "Thailand", "Asia/Bangkok", "+66", ["泰国", "thailand", "asia/bangkok", "+66"]],
["东帝汶", "Timor-Leste", "Asia/Dili", "+670", ["东帝汶", "timor-leste", "asia/dili", "+670"]],
["土库曼斯坦", "Turkmenistan", "Asia/Ashgabat", "+993", ["土库曼斯坦", "turkmenistan", "asia/ashgabat", "+993"]],
["阿联酋", "UAE", "Asia/Dubai", "+971", ["阿联酋", "uae", "asia/dubai", "+971"]],
["乌兹别克斯坦", "Uzbekistan", "Asia/Tashkent", "+998", ["乌兹别克斯坦", "uzbekistan", "asia/tashkent", "+998"]],
["越南", "Vietnam", "Asia/Ho_Chi_Minh", "+84", ["越南", "vietnam", "asia/ho_chi_minh", "+84"]],
["也门", "Yemen", "Asia/Riyadh", "+967", ["也门", "yemen", "asia/riyadh", "+967"]],
["阿尔巴尼亚", "Albania", "Europe/Tirane", "+355", ["阿尔巴尼亚", "albania", "europe/tirane", "+355"]],
["安道尔", "Andorra", "Europe/Andorra", "+376", ["安道尔", "andorra", "europe/andorra", "+376"]],
["奥地利", "Austria", "Europe/Vienna", "+43", ["奥地利", "austria", "europe/vienna", "+43"]],
["白俄罗斯", "Belarus", "Europe/Minsk", "+375", ["白俄罗斯", "belarus", "europe/minsk", "+375"]],
["比利时", "Belgium", "Europe/Brussels", "+32", ["比利时", "belgium", "europe/brussels", "+32"]],
["波黑", "Bosnia", "Europe/Sarajevo", "+387", ["波黑", "bosnia", "europe/sarajevo", "+387"]],
["保加利亚", "Bulgaria", "Europe/Sofia", "+359", ["保加利亚", "bulgaria", "europe/sofia", "+359"]],
["克罗地亚", "Croatia", "Europe/Zagreb", "+385", ["克罗地亚", "croatia", "europe/zagreb", "+385"]],
["塞浦路斯", "Cyprus", "Asia/Nicosia", "+357", ["塞浦路斯", "cyprus", "asia/nicosia", "+357"]],
["捷克", "Czech Republic", "Europe/Prague", "+420", ["捷克", "czech republic", "europe/prague", "+420"]],
["丹麦", "Denmark", "Europe/Copenhagen", "+45", ["丹麦", "denmark", "europe/copenhagen", "+45"]],
["爱沙尼亚", "Estonia", "Europe/Tallinn", "+372", ["爱沙尼亚", "estonia", "europe/tallinn", "+372"]],
["芬兰", "Finland", "Europe/Helsinki", "+358", ["芬兰", "finland", "europe/helsinki", "+358"]],
["法国", "France", "Europe/Paris", "+33", ["法国", "france", "europe/paris", "+33"]],
["德国", "Germany", "Europe/Berlin", "+49", ["德国", "germany", "europe/berlin", "+49"]],
["希腊", "Greece", "Europe/Athens", "+30", ["希腊", "greece", "europe/athens", "+30"]],
["匈牙利", "Hungary", "Europe/Budapest", "+36", ["匈牙利", "hungary", "europe/budapest", "+36"]],
["冰岛", "Iceland", "Atlantic/Reykjavik", "+354", ["冰岛", "iceland", "atlantic/reykjavik", "+354"]],
["爱尔兰", "Ireland", "Europe/Dublin", "+353", ["爱尔兰", "ireland", "europe/dublin", "+353"]],
["意大利", "Italy", "Europe/Rome", "+39", ["意大利", "italy", "europe/rome", "+39"]],
["科索沃", "Kosovo", "Europe/Belgrade", "+383", ["科索沃", "kosovo", "europe/belgrade", "+383"]],
["拉脱维亚", "Latvia", "Europe/Riga", "+371", ["拉脱维亚", "latvia", "europe/riga", "+371"]],
["列支敦士登", "Liechtenstein", "Europe/Zurich", "+423", ["列支敦士登", "liechtenstein", "europe/zurich", "+423"]],
["立陶宛", "Lithuania", "Europe/Vilnius", "+370", ["立陶宛", "lithuania", "europe/vilnius", "+370"]],
["卢森堡", "Luxembourg", "Europe/Luxembourg", "+352", ["卢森堡", "luxembourg", "europe/luxembourg", "+352"]],
["马耳他", "Malta", "Europe/Malta", "+356", ["马耳他", "malta", "europe/malta", "+356"]],
["摩尔多瓦", "Moldova", "Europe/Chisinau", "+373", ["摩尔多瓦", "moldova", "europe/chisinau", "+373"]],
["摩纳哥", "Monaco", "Europe/Monaco", "+377", ["摩纳哥", "monaco", "europe/monaco", "+377"]],
["黑山", "Montenegro", "Europe/Podgorica", "+382", ["黑山", "montenegro", "europe/podgorica", "+382"]],
["荷兰", "Netherlands", "Europe/Amsterdam", "+31", ["荷兰", "netherlands", "europe/amsterdam", "+31"]],
["北马其顿", "North Macedonia", "Europe/Skopje", "+389", ["北马其顿", "north macedonia", "europe/skopje", "+389"]],
["挪威", "Norway", "Europe/Oslo", "+47", ["挪威", "norway", "europe/oslo", "+47"]],
["波兰", "Poland", "Europe/Warsaw", "+48", ["波兰", "poland", "europe/warsaw", "+48"]],
["葡萄牙", "Portugal", "Europe/Lisbon", "+351", ["葡萄牙", "portugal", "europe/lisbon", "+351"]],
["罗马尼亚", "Romania", "Europe/Bucharest", "+40", ["罗马尼亚", "romania", "europe/bucharest", "+40"]],
["俄罗斯", "Russia", "Europe/Moscow", "+7", ["俄罗斯", "russia", "europe/moscow", "+7"]],
["圣马力诺", "San Marino", "Europe/Rome", "+378", ["圣马力诺", "san marino", "europe/rome", "+378"]],
["塞尔维亚", "Serbia", "Europe/Belgrade", "+381", ["塞尔维亚", "serbia", "europe/belgrade", "+381"]],
["斯洛伐克", "Slovakia", "Europe/Bratislava", "+421", ["斯洛伐克", "slovakia", "europe/bratislava", "+421"]],
["斯洛文尼亚", "Slovenia", "Europe/Ljubljana", "+386", ["斯洛文尼亚", "slovenia", "europe/ljubljana", "+386"]],
["西班牙", "Spain", "Europe/Madrid", "+34", ["西班牙", "spain", "europe/madrid", "+34"]],
["瑞典", "Sweden", "Europe/Stockholm", "+46", ["瑞典", "sweden", "europe/stockholm", "+46"]],
["瑞士", "Switzerland", "Europe/Zurich", "+41", ["瑞士", "switzerland", "europe/zurich", "+41"]],
["土耳其", "Turkey", "Europe/Istanbul", "+90", ["土耳其", "turkey", "europe/istanbul", "+90"]],
["乌克兰", "Ukraine", "Europe/Kyiv", "+380", ["乌克兰", "ukraine", "europe/kyiv", "+380"]],
["英国", "United Kingdom", "Europe/London", "+44", ["英国", "united kingdom", "europe/london", "+44"]],
["梵蒂冈", "Vatican", "Europe/Rome", "+379", ["梵蒂冈", "vatican", "europe/rome", "+379"]],
["阿尔及利亚", "Algeria", "Africa/Algiers", "+213", ["阿尔及利亚", "algeria", "africa/algiers", "+213"]],
["安哥拉", "Angola", "Africa/Lagos", "+244", ["安哥拉", "angola", "africa/lagos", "+244"]],
["贝宁", "Benin", "Africa/Lagos", "+229", ["贝宁", "benin", "africa/lagos", "+229"]],
["博茨瓦纳", "Botswana", "Africa/Maputo", "+267", ["博茨瓦纳", "botswana", "africa/maputo", "+267"]],
["布基纳法索", "Burkina Faso", "Africa/Abidjan", "+226", ["布基纳法索", "burkina faso", "africa/abidjan", "+226"]],
["布隆迪", "Burundi", "Africa/Maputo", "+257", ["布隆迪", "burundi", "africa/maputo", "+257"]],
["佛得角", "Cape Verde", "Atlantic/Cape_Verde", "+238", ["佛得角", "cape verde", "atlantic/cape_verde", "+238"]],
["喀麦隆", "Cameroon", "Africa/Lagos", "+237", ["喀麦隆", "cameroon", "africa/lagos", "+237"]],
["中非", "Central African Republic", "Africa/Lagos", "+236", ["中非", "central african republic", "africa/lagos", "+236"]],
["乍得", "Chad", "Africa/Ndjamena", "+235", ["乍得", "chad", "africa/ndjamena", "+235"]],
["科摩罗", "Comoros", "Africa/Nairobi", "+269", ["科摩罗", "comoros", "africa/nairobi", "+269"]],
["刚果布", "Congo", "Africa/Lagos", "+242", ["刚果布", "congo", "africa/lagos", "+242"]],
["刚果金", "DR Congo", "Africa/Lubumbashi", "+243", ["刚果金", "dr congo", "africa/lubumbashi", "+243"]],
["科特迪瓦", "Ivory Coast", "Africa/Abidjan", "+225", ["科特迪瓦", "ivory coast", "africa/abidjan", "+225"]],
["吉布提", "Djibouti", "Africa/Nairobi", "+253", ["吉布提", "djibouti", "africa/nairobi", "+253"]],
["埃及", "Egypt", "Africa/Cairo", "+20", ["埃及", "egypt", "africa/cairo", "+20"]],
["赤道几内亚", "Equatorial Guinea", "Africa/Lagos", "+240", ["赤道几内亚", "equatorial guinea", "africa/lagos", "+240"]],
["厄立特里亚", "Eritrea", "Africa/Nairobi", "+291", ["厄立特里亚", "eritrea", "africa/nairobi", "+291"]],
["埃塞俄比亚", "Ethiopia", "Africa/Nairobi", "+251", ["埃塞俄比亚", "ethiopia", "africa/nairobi", "+251"]],
["加蓬", "Gabon", "Africa/Lagos", "+241", ["加蓬", "gabon", "africa/lagos", "+241"]],
["冈比亚", "Gambia", "Africa/Abidjan", "+220", ["冈比亚", "gambia", "africa/abidjan", "+220"]],
["加纳", "Ghana", "Africa/Abidjan", "+233", ["加纳", "ghana", "africa/abidjan", "+233"]],
["几内亚", "Guinea", "Africa/Abidjan", "+224", ["几内亚", "guinea", "africa/abidjan", "+224"]],
["几内亚比绍", "Guinea-Bissau", "Africa/Bissau", "+245", ["几内亚比绍", "guinea-bissau", "africa/bissau", "+245"]],
["肯尼亚", "Kenya", "Africa/Nairobi", "+254", ["肯尼亚", "kenya", "africa/nairobi", "+254"]],
["莱索托", "Lesotho", "Africa/Johannesburg", "+266", ["莱索托", "lesotho", "africa/johannesburg", "+266"]],
["利比里亚", "Liberia", "Africa/Monrovia", "+231", ["利比里亚", "liberia", "africa/monrovia", "+231"]],
["利比亚", "Libya", "Africa/Tripoli", "+218", ["利比亚", "libya", "africa/tripoli", "+218"]],
["马达加斯加", "Madagascar", "Africa/Nairobi", "+261", ["马达加斯加", "madagascar", "africa/nairobi", "+261"]],
["马拉维", "Malawi", "Africa/Maputo", "+265", ["马拉维", "malawi", "africa/maputo", "+265"]],
["马里", "Mali", "Africa/Abidjan", "+223", ["马里", "mali", "africa/abidjan", "+223"]],
["毛里塔尼亚", "Mauritania", "Africa/Abidjan", "+222", ["毛里塔尼亚", "mauritania", "africa/abidjan", "+222"]],
["毛里求斯", "Mauritius", "Indian/Mauritius", "+230", ["毛里求斯", "mauritius", "indian/mauritius", "+230"]],
["摩洛哥", "Morocco", "Africa/Casablanca", "+212", ["摩洛哥", "morocco", "africa/casablanca", "+212"]],
["莫桑比克", "Mozambique", "Africa/Maputo", "+258", ["莫桑比克", "mozambique", "africa/maputo", "+258"]],
["纳米比亚", "Namibia", "Africa/Windhoek", "+264", ["纳米比亚", "namibia", "africa/windhoek", "+264"]],
["尼日尔", "Niger", "Africa/Lagos", "+227", ["尼日尔", "niger", "africa/lagos", "+227"]],
["尼日利亚", "Nigeria", "Africa/Lagos", "+234", ["尼日利亚", "nigeria", "africa/lagos", "+234"]],
["卢旺达", "Rwanda", "Africa/Maputo", "+250", ["卢旺达", "rwanda", "africa/maputo", "+250"]],
["圣多美", "Sao Tome", "Africa/Sao_Tome", "+239", ["圣多美", "sao tome", "africa/sao_tome", "+239"]],
["塞内加尔", "Senegal", "Africa/Abidjan", "+221", ["塞内加尔", "senegal", "africa/abidjan", "+221"]],
["塞舌尔", "Seychelles", "Indian/Mahe", "+248", ["塞舌尔", "seychelles", "indian/mahe", "+248"]],
["塞拉利昂", "Sierra Leone", "Africa/Abidjan", "+232", ["塞拉利昂", "sierra leone", "africa/abidjan", "+232"]],
["索马里", "Somalia", "Africa/Nairobi", "+252", ["索马里", "somalia", "africa/nairobi", "+252"]],
["南非", "South Africa", "Africa/Johannesburg", "+27", ["南非", "south africa", "africa/johannesburg", "+27"]],
["南苏丹", "South Sudan", "Africa/Juba", "+211", ["南苏丹", "south sudan", "africa/juba", "+211"]],
["苏丹", "Sudan", "Africa/Khartoum", "+249", ["苏丹", "sudan", "africa/khartoum", "+249"]],
["斯威士兰", "Eswatini", "Africa/Johannesburg", "+268", ["斯威士兰", "eswatini", "africa/johannesburg", "+268"]],
["坦桑尼亚", "Tanzania", "Africa/Nairobi", "+255", ["坦桑尼亚", "tanzania", "africa/nairobi", "+255"]],
["多哥", "Togo", "Africa/Abidjan", "+228", ["多哥", "togo", "africa/abidjan", "+228"]],
["突尼斯", "Tunisia", "Africa/Tunis", "+216", ["突尼斯", "tunisia", "africa/tunis", "+216"]],
["乌干达", "Uganda", "Africa/Nairobi", "+256", ["乌干达", "uganda", "africa/nairobi", "+256"]],
["赞比亚", "Zambia", "Africa/Maputo", "+260", ["赞比亚", "zambia", "africa/maputo", "+260"]],
["津巴布韦", "Zimbabwe", "Africa/Maputo", "+263", ["津巴布韦", "zimbabwe", "africa/maputo", "+263"]],
["安提瓜", "Antigua", "America/Puerto_Rico", "+1268", ["安提瓜", "antigua", "america/puerto_rico", "+1268"]],
["巴哈马", "Bahamas", "America/Toronto", "+1242", ["巴哈马", "bahamas", "america/toronto", "+1242"]],
["巴巴多斯", "Barbados", "America/Barbados", "+1246", ["巴巴多斯", "barbados", "america/barbados", "+1246"]],
["伯利兹", "Belize", "America/Belize", "+501", ["伯利兹", "belize", "america/belize", "+501"]],
["加拿大", "Canada", "America/Toronto", "+1", ["加拿大", "canada", "america/toronto", "+1"]],
["哥斯达黎加", "Costa Rica", "America/Costa_Rica", "+506", ["哥斯达黎加", "costa rica", "america/costa_rica", "+506"]],
["古巴", "Cuba", "America/Havana", "+53", ["古巴", "cuba", "america/havana", "+53"]],
["多米尼克", "Dominica", "America/Puerto_Rico", "+1767", ["多米尼克", "dominica", "america/puerto_rico", "+1767"]],
["多米尼加", "Dominican Republic", "America/Santo_Domingo", "+1809", ["多米尼加", "dominican republic", "america/santo_domingo", "+1809"]],
["萨尔瓦多", "El Salvador", "America/El_Salvador", "+503", ["萨尔瓦多", "el salvador", "america/el_salvador", "+503"]],
["格林纳达", "Grenada", "America/Puerto_Rico", "+1473", ["格林纳达", "grenada", "america/puerto_rico", "+1473"]],
["危地马拉", "Guatemala", "America/Guatemala", "+502", ["危地马拉", "guatemala", "america/guatemala", "+502"]],
["海地", "Haiti", "America/Port-au-Prince", "+509", ["海地", "haiti", "america/port-au-prince", "+509"]],
["洪都拉斯", "Honduras", "America/Tegucigalpa", "+504", ["洪都拉斯", "honduras", "america/tegucigalpa", "+504"]],
["牙买加", "Jamaica", "America/Jamaica", "+1876", ["牙买加", "jamaica", "america/jamaica", "+1876"]],
["墨西哥", "Mexico", "America/Mexico_City", "+52", ["墨西哥", "mexico", "america/mexico_city", "+52"]],
["尼加拉瓜", "Nicaragua", "America/Managua", "+505", ["尼加拉瓜", "nicaragua", "america/managua", "+505"]],
["巴拿马", "Panama", "America/Panama", "+507", ["巴拿马", "panama", "america/panama", "+507"]],
["波多黎各", "Puerto Rico", "America/Puerto_Rico", "+1787", ["波多黎各", "puerto rico", "america/puerto_rico", "+1787"]],
["圣基茨", "St Kitts", "America/Puerto_Rico", "+1869", ["圣基茨", "st kitts", "america/puerto_rico", "+1869"]],
["圣卢西亚", "St Lucia", "America/Puerto_Rico", "+1758", ["圣卢西亚", "st lucia", "america/puerto_rico", "+1758"]],
["圣文森特", "St Vincent", "America/Puerto_Rico", "+1784", ["圣文森特", "st vincent", "america/puerto_rico", "+1784"]],
["特立尼达", "Trinidad", "America/Puerto_Rico", "+1868", ["特立尼达", "trinidad", "america/puerto_rico", "+1868"]],
["美国", "United States", "America/New_York", "+1", ["美国", "united states", "america/new_york", "+1"]],
["阿根廷", "Argentina", "America/Argentina/Buenos_Aires", "+54", ["阿根廷", "argentina", "america/argentina/buenos_aires", "+54"]],
["玻利维亚", "Bolivia", "America/La_Paz", "+591", ["玻利维亚", "bolivia", "america/la_paz", "+591"]],
["巴西", "Brazil", "America/Sao_Paulo", "+55", ["巴西", "brazil", "america/sao_paulo", "+55"]],
["智利", "Chile", "America/Santiago", "+56", ["智利", "chile", "america/santiago", "+56"]],
["哥伦比亚", "Colombia", "America/Bogota", "+57", ["哥伦比亚", "colombia", "america/bogota", "+57"]],
["厄瓜多尔", "Ecuador", "America/Guayaquil", "+593", ["厄瓜多尔", "ecuador", "america/guayaquil", "+593"]],
["圭亚那", "Guyana", "America/Guyana", "+592", ["圭亚那", "guyana", "america/guyana", "+592"]],
["巴拉圭", "Paraguay", "America/Asuncion", "+595", ["巴拉圭", "paraguay", "america/asuncion", "+595"]],
["秘鲁", "Peru", "America/Lima", "+51", ["秘鲁", "peru", "america/lima", "+51"]],
["苏里南", "Suriname", "America/Paramaribo", "+597", ["苏里南", "suriname", "america/paramaribo", "+597"]],
["乌拉圭", "Uruguay", "America/Montevideo", "+598", ["乌拉圭", "uruguay", "america/montevideo", "+598"]],
["委内瑞拉", "Venezuela", "America/Caracas", "+58", ["委内瑞拉", "venezuela", "america/caracas", "+58"]],
["澳大利亚", "Australia", "Australia/Sydney", "+61", ["澳大利亚", "australia", "australia/sydney", "+61"]],
["斐济", "Fiji", "Pacific/Fiji", "+679", ["斐济", "fiji", "pacific/fiji", "+679"]],
["基里巴斯", "Kiribati", "Pacific/Kiritimati", "+686", ["基里巴斯", "kiribati", "pacific/kiritimati", "+686"]],
["马绍尔群岛", "Marshall Islands", "Pacific/Majuro", "+692", ["马绍尔群岛", "marshall islands", "pacific/majuro", "+692"]],
["密克罗尼西亚", "Micronesia", "Pacific/Chuuk", "+691", ["密克罗尼西亚", "micronesia", "pacific/chuuk", "+691"]],
["瑙鲁", "Nauru", "Pacific/Nauru", "+674", ["瑙鲁", "nauru", "pacific/nauru", "+674"]],
["新西兰", "New Zealand", "Pacific/Auckland", "+64", ["新西兰", "new zealand", "pacific/auckland", "+64"]],
["帕劳", "Palau", "Pacific/Palau", "+680", ["帕劳", "palau", "pacific/palau", "+680"]],
["巴布亚新几内亚", "Papua New Guinea", "Pacific/Port_Moresby", "+675", ["巴布亚新几内亚", "papua new guinea", "pacific/port_moresby", "+675"]],
["萨摩亚", "Samoa", "Pacific/Apia", "+685", ["萨摩亚", "samoa", "pacific/apia", "+685"]],
["所罗门群岛", "Solomon Islands", "Pacific/Guadalcanal", "+677", ["所罗门群岛", "solomon islands", "pacific/guadalcanal", "+677"]],
["汤加", "Tonga", "Pacific/Tongatapu", "+676", ["汤加", "tonga", "pacific/tongatapu", "+676"]],
["图瓦卢", "Tuvalu", "Pacific/Funafuti", "+688", ["图瓦卢", "tuvalu", "pacific/funafuti", "+688"]],
["瓦努阿图", "Vanuatu", "Pacific/Efate", "+678", ["瓦努阿图", "vanuatu", "pacific/efate", "+678"]],
["关岛", "Guam", "Pacific/Guam", "+1671", ["关岛", "guam", "pacific/guam", "+1671"]],
["新喀里多尼亚", "New Caledonia", "Pacific/Noumea", "+687", ["新喀里多尼亚", "new caledonia", "pacific/noumea", "+687"]],
["法属波利尼西亚", "French Polynesia", "Pacific/Tahiti", "+689", ["法属波利尼西亚", "french polynesia", "pacific/tahiti", "+689"]]];
